lib_sourcedir := ./src
lib_c_sources := \
	xcore_c_inlines.c

lib_asm_sources := \
	xcore_c_interrupt.S \
	xcore_c_select.S \
	xcore_c_thread.S

lib_xc_sources := 
lib_name := xcore_c
lib_incdirs := \
	./api \
	../../lib_xassert/lib_xassert/api

include xlib.mk

