// Copyright (c) 2019-2020, XMOS Ltd, All rights reserved
#pragma once

#define _XCORE_SHIM(FLM, ...) FLM(__VA_ARGS__)
#define _XCORE_UNIQUE_LABEL_I(BNAME, CNT) BNAME ## CNT
#define _XCORE_UNIQUE_LABEL(BNAME) _XCORE_SHIM(_XCORE_UNIQUE_LABEL_I, BNAME, __COUNTER__)
#define _XCORE_STRINGIFY_I(S) #S
#define _XCORE_STRINGIFY(S) _XCORE_STRINGIFY_I(S)

#define _XCORE_SEP__XCORE_SEP_COMMA ,
#define _XCORE_SEP__XCORE_SEP_SEMICOLON ;
#define _XCORE_SEP__XCORE_SEP_NONE

#define _XCORE_APPLY0(F, SEP)
#define _XCORE_APPLY1(F, SEP, A0, ...) F(A0) _XCORE_APPLY0(F, SEP, ## __VA_ARGS__)
#define _XCORE_APPLY2(F, SEP, A0, ...) F(A0) _XCORE_SEP_##SEP _XCORE_APPLY1(F, SEP, __VA_ARGS__)
#define _XCORE_APPLY3(F, SEP, A0, ...) F(A0) _XCORE_SEP_##SEP _XCORE_APPLY2(F, SEP, __VA_ARGS__)
#define _XCORE_APPLY4(F, SEP, A0, ...) F(A0) _XCORE_SEP_##SEP _XCORE_APPLY3(F, SEP, __VA_ARGS__)
#define _XCORE_APPLY5(F, SEP, A0, ...) F(A0) _XCORE_SEP_##SEP _XCORE_APPLY4(F, SEP, __VA_ARGS__)
#define _XCORE_APPLY6(F, SEP, A0, ...) F(A0) _XCORE_SEP_##SEP _XCORE_APPLY5(F, SEP, __VA_ARGS__)
#define _XCORE_APPLY7(F, SEP, A0, ...) F(A0) _XCORE_SEP_##SEP _XCORE_APPLY6(F, SEP, __VA_ARGS__)
#define _XCORE_APPLY8(F, SEP, A0, ...) F(A0) _XCORE_SEP_##SEP _XCORE_APPLY7(F, SEP, __VA_ARGS__)
#define _XCORE_APPLY9(F, SEP, A0, ...) F(A0) _XCORE_SEP_##SEP _XCORE_APPLY8(F, SEP, __VA_ARGS__)
#define _XCORE_APPLY10(F, SEP, A0, ...) F(A0) _XCORE_SEP_##SEP _XCORE_APPLY9(F, SEP, __VA_ARGS__)

#define _XCORE_GET10(I0, I1, I2, I3, I4, T5, T6, T7, T8, T9, N, ...) N
#define _XCORE_APPLICATOR(...) _XCORE_GET10(__VA_ARGS__, _XCORE_APPLY10, _XCORE_APPLY9, _XCORE_APPLY8, _XCORE_APPLY7, _XCORE_APPLY6, _XCORE_APPLY5, _XCORE_APPLY4, _XCORE_APPLY3, _XCORE_APPLY2, _XCORE_APPLY1, _XCORE_APPLY0)

#define _XCORE_APPLY_I(F, SEP, ...) _XCORE_APPLICATOR(__VA_ARGS__)(F, SEP, ## __VA_ARGS__)
#define _XCORE_APPLY(F, ...) _XCORE_APPLY_I(F, _XCORE_SEP_COMMA, ## __VA_ARGS__)
#define _XCORE_APPLY_NOSEP(F, ...) _XCORE_APPLY_I(F, _XCORE_SEP_NONE, ## __VA_ARGS__)
#define _XCORE_LABELADDR(LABEL) &&LABEL

#define _XCORE_DEPAREN(...) __VA_ARGS__
#define _XCORE_UNPACK(PACK) _XCORE_DEPAREN PACK
#define _XCORE_PSHIM(FLM, PACK, ...) _XCORE_SHIM(FLM, _XCORE_UNPACK(PACK), ## __VA_ARGS__)
#define _XCORE_PSHIM_NV(FLM, PACK) _XCORE_SHIM(_XCORE_SHIM, FLM, _XCORE_UNPACK(PACK))

#define _XCORE_TAIL(H_, ...) __VA_ARGS__
#define _XCORE_HEAD(H, ...) H

#define _XCORE_I(...) __VA_ARGS__
#define _XCORE_PACK_JOIN(LHS, RHS) (_XCORE_DEPAREN LHS, _XCORE_DEPAREN RHS)



#define _XCORE_TAG0(T_)
#define _XCORE_TAG1(T, V, ...) (T,V) _XCORE_TAG0(T, ## __VA_ARGS__)
#define _XCORE_TAG2(T, V, ...) (T,V), _XCORE_TAG1(T, __VA_ARGS__)
#define _XCORE_TAG3(T, V, ...) (T,V), _XCORE_TAG2(T, __VA_ARGS__)
#define _XCORE_TAG4(T, V, ...) (T,V), _XCORE_TAG3(T, __VA_ARGS__)
#define _XCORE_TAG5(T, V, ...) (T,V), _XCORE_TAG4(T, __VA_ARGS__)
#define _XCORE_TAG6(T, V, ...) (T,V), _XCORE_TAG5(T, __VA_ARGS__)
#define _XCORE_TAG7(T, V, ...) (T,V), _XCORE_TAG6(T, __VA_ARGS__)
#define _XCORE_TAG8(T, V, ...) (T,V), _XCORE_TAG7(T, __VA_ARGS__)
#define _XCORE_TAG9(T, V, ...) (T,V), _XCORE_TAG8(T, __VA_ARGS__)
#define _XCORE_TAG10(T, V, ...) (T,V), _XCORE_TAG9(T, __VA_ARGS__)

#define _XCORE_TAGGER(...) _XCORE_GET10(__VA_ARGS__, _XCORE_TAG10, _XCORE_TAG9, _XCORE_TAG8, _XCORE_TAG7, _XCORE_TAG6, _XCORE_TAG5, _XCORE_TAG4, _XCORE_TAG3, _XCORE_TAG2, _XCORE_TAG1, _XCORE_TAG0)
#define _XCORE_TAG(T, ...)  _XCORE_TAGGER(__VA_ARGS__)(T, ## __VA_ARGS__)
#define _XCORE_PACK(...) (__VA_ARGS__)

#define _XCORE_COUNT10(...) _XCORE_GET10(__VA_ARGS__, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)
