lib_sourcedir := ./src
lib_c_sources := \
	xcore_c_resource.c \
	xcore_c_inlines.c \
	xcore_c_state.c

lib_asm_sources := \
	xcore_c_interrupt.S \
	xcore_c_select.S \
	xcore_c_thread.S

lib_xc_sources := 
lib_name := xcore
lib_incdirs := \
	./api \

include xlib.mk

